# An ansible playbook that sets up a tricked-out vim/zsh/tmux environment
#
# Based on work by: Luke Macken <lmacken@redhat.com>
---

- name: Bootstrapping developer environment
  hosts: all

  tasks:

  - name: Determining username
    action: shell whoami
    register: whoami
    sudo: False

  - name: Installing zsh, vim, git, tmux, etc.
    apt: pkg={{item}} state=installed update_cache=yes
    sudo: True
    with_items:
    - zsh
    - vim
    - git
    - tmux
    - htop
    - curl

  - name: Changing the default shell to zsh
    user: name=vagrant shell=/bin/zsh
    sudo: True

- name: Entering Plugin Nirvana
  hosts: all
  sudo: False

  tasks:

  - name: Installing oh-my-zsh (https://github.com/robbyrussell/oh-my-zsh)
    action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh

  - name: Installing Prose Theme for zsh
    action: shell curl https://raw.githubusercontent.com/tijptjik/oh-my-zsh/master/themes/prose.zsh-theme > ~/.oh-my-zsh/prose.zsh.theme

  - name: Creating new ~/.zshrc
    action: shell curl https://gist.githubusercontent.com/tijptjik/7f080665dbea81ae97f8/raw > ~/.zshrc

  # - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
    # action: shell curl http://j.mp/spf13-vim3 -L -o - | sh

